export const userConstants = {
    LOGIN_NO_ACTION: 'LOGIN_NO_ACTION',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    REGISTER_NO_ACTION: 'REGISTER_NO_ACTION',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    CHANGE_ACCOUNT: 'CHANGE_ACCOUNT',

    LOGOUT: 'LOGOUT'
}